services:
  - type: web
    name: news-agent-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn src.main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

